dataset: ogbg-mollipo

# learning
batch_size: 128

# diffusion-based augmentation
n_negative: 1
out_steps: 1
topk: 20
aug_batch: 5000
start: 50
iteration: 10
strategy: replace_accumulate
snr: 0.2
scale_eps: 0
perturb_ratio: 0.01

no_print: True